/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    ChainlinkPriceSource: {
      address: "0x05956Cca58B1CAEE6Bd798FFD85c0103B363387e",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "uint8",
              name: "registered",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "nowReported",
              type: "uint8",
            },
          ],
          name: "DecimalsChanged",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "reported",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "target",
              type: "uint8",
            },
          ],
          name: "DecimalsTooLarge",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "FeedNotRegistered",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "uint80",
              name: "roundId",
              type: "uint80",
            },
            {
              internalType: "uint80",
              name: "answeredInRound",
              type: "uint80",
            },
          ],
          name: "IncompleteRound",
          type: "error",
        },
        {
          inputs: [],
          name: "MaxAgeRequired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "given",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "limit",
              type: "uint64",
            },
          ],
          name: "MaxAgeTooLarge",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
          ],
          name: "NegativePrice",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "updatedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "nowTs",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "maxAge",
              type: "uint64",
            },
          ],
          name: "ObservationStale",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "aggregator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "maxAge",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "decimals",
              type: "uint8",
            },
          ],
          name: "FeedRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "FeedRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "OwnerChanged",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_CONFIGURABLE_AGE",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TARGET_DECIMALS",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "latest",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "value",
                  type: "uint256",
                },
                {
                  internalType: "uint64",
                  name: "observedAt",
                  type: "uint64",
                },
                {
                  internalType: "bytes32",
                  name: "feedId",
                  type: "bytes32",
                },
              ],
              internalType: "struct IPriceSource.Observation",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "maxAgeOf",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "aggregator",
              type: "address",
            },
            {
              internalType: "uint64",
              name: "maxAge",
              type: "uint64",
            },
          ],
          name: "registerFeed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "removeFeed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "supportsAsset",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        latest: "contracts/IPriceSource.sol",
        maxAgeOf: "contracts/IPriceSource.sol",
        supportsAsset: "contracts/IPriceSource.sol",
      },
      deployedOnBlock: 40805566,
    },
    PolicyRegistry: {
      address: "0xa940AdB6D97BaD78cddF5c451b8Ce05EE6EdECEF",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              internalType: "uint256",
              name: "nowTs",
              type: "uint256",
            },
          ],
          name: "AlreadyExpired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              internalType: "uint256",
              name: "nowTs",
              type: "uint256",
            },
          ],
          name: "ExpiryInPast",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "enum PolicyRegistry.State",
              name: "from",
              type: "uint8",
            },
            {
              internalType: "enum PolicyRegistry.State",
              name: "to",
              type: "uint8",
            },
          ],
          name: "IllegalTransition",
          type: "error",
        },
        {
          inputs: [],
          name: "NotCreator",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "NotSettlement",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              internalType: "uint256",
              name: "nowTs",
              type: "uint256",
            },
          ],
          name: "NotYetExpired",
          type: "error",
        },
        {
          inputs: [],
          name: "NothingToFund",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxPayout",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "escrow",
              type: "uint256",
            },
          ],
          name: "PayoutExceedsEscrow",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "UnknownPolicy",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "OwnerChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "beneficiary",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "threshold",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "triggerAbove",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxPayout",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
          ],
          name: "PolicyCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "PolicyExpired",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "escrow",
              type: "uint256",
            },
          ],
          name: "PolicyFunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PolicyRefunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "beneficiary",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PolicySettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "observedAt",
              type: "uint64",
            },
          ],
          name: "PolicyTriggered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "SettlementChanged",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "conditionMet",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "beneficiary",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "threshold",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "triggerAbove",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "maxPayout",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
          ],
          name: "createPolicy",
          outputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "expire",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "fund",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "getPolicy",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "beneficiary",
                  type: "address",
                },
                {
                  internalType: "bytes32",
                  name: "asset",
                  type: "bytes32",
                },
                {
                  internalType: "uint256",
                  name: "maxPayout",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "escrow",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "threshold",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "triggerAbove",
                  type: "bool",
                },
                {
                  internalType: "uint64",
                  name: "expiry",
                  type: "uint64",
                },
                {
                  internalType: "enum PolicyRegistry.State",
                  name: "state",
                  type: "uint8",
                },
                {
                  internalType: "uint64",
                  name: "triggeredAt",
                  type: "uint64",
                },
                {
                  internalType: "uint256",
                  name: "triggerPrice",
                  type: "uint256",
                },
              ],
              internalType: "struct PolicyRegistry.Policy",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "observedAt",
              type: "uint64",
            },
          ],
          name: "markTriggered",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "nextPolicyId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "refund",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "setSettlement",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "settle",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "settlement",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "stateOf",
          outputs: [
            {
              internalType: "enum PolicyRegistry.State",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalEscrowed",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40805573,
    },
    Settlement: {
      address: "0x7710BbaDcC568f52306a13ec2976517EcdE4abcc",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "registry_",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "threshold",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "triggerAbove",
              type: "bool",
            },
          ],
          name: "ConditionNotMet",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "NoPriceSource",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "source",
              type: "address",
            },
          ],
          name: "SourceDoesNotSupport",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "OwnerChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "source",
              type: "address",
            },
          ],
          name: "PriceSourceSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "observedAt",
              type: "uint64",
            },
          ],
          name: "TriggerAccepted",
          type: "event",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "preview",
          outputs: [
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "observedAt",
              type: "uint64",
            },
            {
              internalType: "bool",
              name: "conditionMet",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "priceSourceOf",
          outputs: [
            {
              internalType: "contract IPriceSource",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "registry",
          outputs: [
            {
              internalType: "contract PolicyRegistry",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "source",
              type: "address",
            },
          ],
          name: "setPriceSource",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "trigger",
          outputs: [
            {
              internalType: "uint256",
              name: "paid",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40805579,
    },
  },
  31337: {
    ChainlinkPriceSource: {
      address: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "uint8",
              name: "registered",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "nowReported",
              type: "uint8",
            },
          ],
          name: "DecimalsChanged",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "reported",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "target",
              type: "uint8",
            },
          ],
          name: "DecimalsTooLarge",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "FeedNotRegistered",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "uint80",
              name: "roundId",
              type: "uint80",
            },
            {
              internalType: "uint80",
              name: "answeredInRound",
              type: "uint80",
            },
          ],
          name: "IncompleteRound",
          type: "error",
        },
        {
          inputs: [],
          name: "MaxAgeRequired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "given",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "limit",
              type: "uint64",
            },
          ],
          name: "MaxAgeTooLarge",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
          ],
          name: "NegativePrice",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "updatedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "nowTs",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "maxAge",
              type: "uint64",
            },
          ],
          name: "ObservationStale",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "aggregator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "maxAge",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "decimals",
              type: "uint8",
            },
          ],
          name: "FeedRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "FeedRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "OwnerChanged",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_CONFIGURABLE_AGE",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TARGET_DECIMALS",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "latest",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "value",
                  type: "uint256",
                },
                {
                  internalType: "uint64",
                  name: "observedAt",
                  type: "uint64",
                },
                {
                  internalType: "bytes32",
                  name: "feedId",
                  type: "bytes32",
                },
              ],
              internalType: "struct IPriceSource.Observation",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "maxAgeOf",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "aggregator",
              type: "address",
            },
            {
              internalType: "uint64",
              name: "maxAge",
              type: "uint64",
            },
          ],
          name: "registerFeed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "removeFeed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "supportsAsset",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        latest: "contracts/IPriceSource.sol",
        maxAgeOf: "contracts/IPriceSource.sol",
        supportsAsset: "contracts/IPriceSource.sol",
      },
      deployedOnBlock: 8,
    },
    MockAggregatorV3: {
      address: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
      abi: [
        {
          inputs: [
            {
              internalType: "uint8",
              name: "decimals_",
              type: "uint8",
            },
            {
              internalType: "int256",
              name: "answer_",
              type: "int256",
            },
            {
              internalType: "uint256",
              name: "updatedAt_",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "description",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "latestRoundData",
          outputs: [
            {
              internalType: "uint80",
              name: "roundId",
              type: "uint80",
            },
            {
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
            {
              internalType: "uint256",
              name: "startedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "updatedAt",
              type: "uint256",
            },
            {
              internalType: "uint80",
              name: "answeredInRound",
              type: "uint80",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "age",
              type: "uint256",
            },
          ],
          name: "setAgeSeconds",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "answer_",
              type: "int256",
            },
          ],
          name: "setAnswer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "decimals_",
              type: "uint8",
            },
          ],
          name: "setDecimals",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint80",
              name: "roundId_",
              type: "uint80",
            },
            {
              internalType: "uint80",
              name: "answeredInRound_",
              type: "uint80",
            },
          ],
          name: "setRounds",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "updatedAt_",
              type: "uint256",
            },
          ],
          name: "setUpdatedAt",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        decimals: "contracts/interfaces/IAggregatorV3.sol",
        description: "contracts/interfaces/IAggregatorV3.sol",
        latestRoundData: "contracts/interfaces/IAggregatorV3.sol",
      },
      deployedOnBlock: 14,
    },
    PolicyRegistry: {
      address: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              internalType: "uint256",
              name: "nowTs",
              type: "uint256",
            },
          ],
          name: "AlreadyExpired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              internalType: "uint256",
              name: "nowTs",
              type: "uint256",
            },
          ],
          name: "ExpiryInPast",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "enum PolicyRegistry.State",
              name: "from",
              type: "uint8",
            },
            {
              internalType: "enum PolicyRegistry.State",
              name: "to",
              type: "uint8",
            },
          ],
          name: "IllegalTransition",
          type: "error",
        },
        {
          inputs: [],
          name: "NotCreator",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "NotSettlement",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              internalType: "uint256",
              name: "nowTs",
              type: "uint256",
            },
          ],
          name: "NotYetExpired",
          type: "error",
        },
        {
          inputs: [],
          name: "NothingToFund",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxPayout",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "escrow",
              type: "uint256",
            },
          ],
          name: "PayoutExceedsEscrow",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "UnknownPolicy",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "OwnerChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "beneficiary",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "threshold",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "triggerAbove",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxPayout",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
          ],
          name: "PolicyCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "PolicyExpired",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "escrow",
              type: "uint256",
            },
          ],
          name: "PolicyFunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PolicyRefunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "beneficiary",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PolicySettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "observedAt",
              type: "uint64",
            },
          ],
          name: "PolicyTriggered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "SettlementChanged",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "conditionMet",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "beneficiary",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "threshold",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "triggerAbove",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "maxPayout",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
          ],
          name: "createPolicy",
          outputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "expire",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "fund",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "getPolicy",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "beneficiary",
                  type: "address",
                },
                {
                  internalType: "bytes32",
                  name: "asset",
                  type: "bytes32",
                },
                {
                  internalType: "uint256",
                  name: "maxPayout",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "escrow",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "threshold",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "triggerAbove",
                  type: "bool",
                },
                {
                  internalType: "uint64",
                  name: "expiry",
                  type: "uint64",
                },
                {
                  internalType: "enum PolicyRegistry.State",
                  name: "state",
                  type: "uint8",
                },
                {
                  internalType: "uint64",
                  name: "triggeredAt",
                  type: "uint64",
                },
                {
                  internalType: "uint256",
                  name: "triggerPrice",
                  type: "uint256",
                },
              ],
              internalType: "struct PolicyRegistry.Policy",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "observedAt",
              type: "uint64",
            },
          ],
          name: "markTriggered",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "nextPolicyId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "refund",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "setSettlement",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "settle",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "settlement",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "stateOf",
          outputs: [
            {
              internalType: "enum PolicyRegistry.State",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalEscrowed",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10,
    },
    Settlement: {
      address: "0x0165878A594ca255338adfa4d48449f69242Eb8F",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "registry_",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "threshold",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "triggerAbove",
              type: "bool",
            },
          ],
          name: "ConditionNotMet",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
          ],
          name: "NoPriceSource",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "source",
              type: "address",
            },
          ],
          name: "SourceDoesNotSupport",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "OwnerChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "source",
              type: "address",
            },
          ],
          name: "PriceSourceSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "observedAt",
              type: "uint64",
            },
          ],
          name: "TriggerAccepted",
          type: "event",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "preview",
          outputs: [
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "observedAt",
              type: "uint64",
            },
            {
              internalType: "bool",
              name: "conditionMet",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "priceSourceOf",
          outputs: [
            {
              internalType: "contract IPriceSource",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "registry",
          outputs: [
            {
              internalType: "contract PolicyRegistry",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "asset",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "source",
              type: "address",
            },
          ],
          name: "setPriceSource",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "trigger",
          outputs: [
            {
              internalType: "uint256",
              name: "paid",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 12,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
